### ISSUE TITLE
trouble populating .tags

### ISSUE THREAD

**Issue by tsengf** [universal-ctags/citre#124] opened 2022-05-16 17:49 UTC
When I run citre-create-tags-file, it brings me to a buffer that allows me to customize the ctags command.

ctags
-o
%TAGSFILE%
--languages=C,C++ ;; programming languages to be scanned
--kinds-all=*
--fields=*
--extras=*
-R
;; add dirs/files to scan here, one line per dir/file

With C-c C-c, I notice that the source files are not indexed, and I end up with more or less an empty .tags file. The comment ";; programming languages to be scanned." seems to be causing this. When I remove this comment, the source files are properly indexed.

**Comment by AmaiKinono** [comment] 2022-05-17 00:22
Duplicate of https://github.com/universal-ctags/citre/issues/123.

Please update to the latest version, *delete the generated tags file* and try again. It will work.

**Closed by AmaiKinono** 2022-05-17 00:22 UTC

**Comment by tsengf** [comment] 2022-05-17 00:24
I did a clone last night which should be up to date right?

**Comment by AmaiKinono** [comment] 2022-05-17 00:27
Did you delete the previously created tags file?

**Comment by tsengf** [comment] 2022-05-17 00:27
Yes

**Comment by AmaiKinono** [comment] 2022-05-17 00:37
;) glad to hear that. Have fun with Citre!
